"""
Secure sandboxing system for AlphaEvolve code execution.

This module provides sandboxing capabilities to safely execute potentially
untrusted code generated by LLMs in isolated environments.
"""

import asyncio
import json
import logging
import os
import tempfile
import time
import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

try:
    import docker
    DOCKER_AVAILABLE = True
except ImportError:
    DOCKER_AVAILABLE = False


@dataclass
class ResourceLimits:
    """Configuration for resource limits in sandbox execution."""
    cpu_limit: float = 1.0  # CPU cores (e.g., 0.5 for half a core)
    memory_limit: str = "256m"  # Memory limit (e.g., "256m", "1g")
    timeout_seconds: int = 30  # Maximum execution time
    max_output_size: int = 1024 * 1024  # Maximum output size in bytes (1MB)
    network_disabled: bool = True  # Disable network access


@dataclass 
class SandboxResult:
    """Result of sandbox execution."""
    success: bool
    stdout: str = ""
    stderr: str = ""
    return_code: int = 0
    execution_time: float = 0.0
    error_message: str = ""
    resource_usage: Optional[Dict[str, Any]] = None


class SandboxError(Exception):
    """Exception raised for sandbox-related errors."""
    pass


class Sandbox(ABC):
    """Abstract base class for code execution sandboxes."""
    
    def __init__(self, resource_limits: Optional[ResourceLimits] = None):
        """
        Initialize the sandbox with resource limits.
        
        Args:
            resource_limits: Resource constraints for execution
        """
        self.resource_limits = resource_limits or ResourceLimits()
        self.logger = logging.getLogger(self.__class__.__name__)
        
    @abstractmethod
    async def execute(self, code: str, inputs: Optional[Dict[str, Any]] = None) -> SandboxResult:
        """
        Execute code in the sandbox.
        
        Args:
            code: Python code to execute
            inputs: Optional input data for the code
            
        Returns:
            SandboxResult containing execution outcome
        """
        pass
        
    @abstractmethod
    def cleanup(self) -> None:
        """Clean up sandbox resources."""
        pass


class DockerSandbox(Sandbox):
    """Docker-based sandbox for secure code execution."""
    
    SANDBOX_IMAGE = "alphaevolve-sandbox:latest"
    
    def __init__(self, resource_limits: Optional[ResourceLimits] = None):
        """
        Initialize Docker sandbox.
        
        Args:
            resource_limits: Resource constraints for execution
            
        Raises:
            SandboxError: If Docker is not available
        """
        if not DOCKER_AVAILABLE:
            raise SandboxError("Docker is not available. Install docker package: pip install docker")
            
        super().__init__(resource_limits)
        
        try:
            self.client = docker.from_env()
            # Test Docker connection
            self.client.ping()
        except Exception as e:
            raise SandboxError(f"Failed to connect to Docker: {e}")
            
        self.containers_to_cleanup: List[str] = []
        
    async def execute(self, code: str, inputs: Optional[Dict[str, Any]] = None) -> SandboxResult:
        """
        Execute code in a Docker container.
        
        Args:
            code: Python code to execute
            inputs: Optional input data for the code
            
        Returns:
            SandboxResult containing execution outcome
        """
        start_time = time.time()
        container_id = None
        
        try:
            # Ensure sandbox image exists
            await self._ensure_sandbox_image()
            
            # Prepare execution environment
            execution_id = str(uuid.uuid4())
            with tempfile.TemporaryDirectory() as temp_dir:
                code_file = Path(temp_dir) / "code.py"
                
                # Write code to file
                code_file.write_text(code)
                
                # Configure container
                container_config = self._get_container_config(temp_dir)
                
                # Start container with direct Python execution
                container = await asyncio.get_event_loop().run_in_executor(
                    None, 
                    lambda: self.client.containers.run(
                        self.SANDBOX_IMAGE,
                        command=f"python /sandbox/code.py",
                        **container_config
                    )
                )
                
                container_id = container.id
                self.containers_to_cleanup.append(container_id)
                
                # Wait for execution with timeout
                try:
                    exit_code = await asyncio.wait_for(
                        asyncio.get_event_loop().run_in_executor(
                            None, container.wait
                        ),
                        timeout=self.resource_limits.timeout_seconds
                    )
                    exit_code = exit_code['StatusCode']
                except asyncio.TimeoutError:
                    # Kill container on timeout
                    await asyncio.get_event_loop().run_in_executor(
                        None, container.kill
                    )
                    execution_time = time.time() - start_time
                    return SandboxResult(
                        success=False,
                        return_code=-1,
                        execution_time=execution_time,
                        error_message=f"Execution timed out after {self.resource_limits.timeout_seconds} seconds"
                    )
                
                # Get logs
                logs = await asyncio.get_event_loop().run_in_executor(
                    None, lambda: container.logs(stdout=True, stderr=True)
                )
                
                # Parse stdout and stderr
                stdout = ""
                stderr = ""
                if logs:
                    logs_str = logs.decode('utf-8', errors='replace')
                    # Docker logs format: stdout/stderr are interleaved
                    stdout = logs_str
                
                # Simple direct execution - no output file parsing needed
                
                execution_time = time.time() - start_time
                
                # Get resource usage stats
                stats = await self._get_container_stats(container)
                
                return SandboxResult(
                    success=(exit_code == 0),
                    stdout=stdout[:self.resource_limits.max_output_size],
                    stderr=stderr[:self.resource_limits.max_output_size],
                    return_code=exit_code,
                    execution_time=execution_time,
                    resource_usage=stats
                )
                
        except Exception as e:
            execution_time = time.time() - start_time
            self.logger.error(f"Docker sandbox execution failed: {e}")
            return SandboxResult(
                success=False,
                execution_time=execution_time,
                error_message=f"Sandbox execution failed: {str(e)}"
            )
        finally:
            # Clean up container
            if container_id:
                try:
                    await asyncio.get_event_loop().run_in_executor(
                        None, 
                        lambda: self.client.containers.get(container_id).remove(force=True)
                    )
                    if container_id in self.containers_to_cleanup:
                        self.containers_to_cleanup.remove(container_id)
                except Exception as e:
                    self.logger.warning(f"Failed to clean up container {container_id}: {e}")
    
    def _get_container_config(self, host_dir: str) -> Dict[str, Any]:
        """Get Docker container configuration."""
        return {
            'detach': True,
            'mem_limit': self.resource_limits.memory_limit,
            'cpu_quota': int(self.resource_limits.cpu_limit * 100000),  # CPU quota in microseconds
            'cpu_period': 100000,  # Standard CPU period (100ms)
            'network_disabled': self.resource_limits.network_disabled,
            'volumes': {
                host_dir: {'bind': '/sandbox', 'mode': 'rw'}
            },
            'working_dir': '/sandbox',
            'user': 'nobody:nogroup',  # Run as non-root user
            'read_only': True,  # Read-only filesystem
            'tmpfs': {'/tmp': 'rw,noexec,nosuid,size=100m'},  # Writable tmp with restrictions
            'security_opt': ['no-new-privileges:true'],  # Security hardening
            'cap_drop': ['ALL'],  # Drop all capabilities
            'remove': False  # We'll remove manually for proper cleanup
        }
    
    async def _get_container_stats(self, container) -> Dict[str, Any]:
        """Get container resource usage statistics."""
        try:
            stats = await asyncio.get_event_loop().run_in_executor(
                None, container.stats, False
            )
            
            # Parse CPU and memory usage
            cpu_usage = 0.0
            memory_usage = 0
            
            if 'cpu_stats' in stats:
                cpu_delta = stats['cpu_stats']['cpu_usage']['total_usage'] - \
                           stats['precpu_stats']['cpu_usage']['total_usage']
                system_delta = stats['cpu_stats']['system_cpu_usage'] - \
                              stats['precpu_stats']['system_cpu_usage']
                if system_delta > 0:
                    cpu_usage = (cpu_delta / system_delta) * 100.0
            
            if 'memory_stats' in stats:
                memory_usage = stats['memory_stats'].get('usage', 0)
            
            return {
                'cpu_usage_percent': cpu_usage,
                'memory_usage_bytes': memory_usage,
                'memory_limit_bytes': stats.get('memory_stats', {}).get('limit', 0)
            }
        except Exception:
            return {}
    
    async def _ensure_sandbox_image(self) -> None:
        """Ensure the sandbox Docker image exists."""
        try:
            # Check if image exists
            await asyncio.get_event_loop().run_in_executor(
                None, self.client.images.get, self.SANDBOX_IMAGE
            )
        except docker.errors.ImageNotFound:
            # Build the image
            self.logger.info(f"Building sandbox image: {self.SANDBOX_IMAGE}")
            await self._build_sandbox_image()
    
    async def _build_sandbox_image(self) -> None:
        """Build the Docker sandbox image."""
        dockerfile_content = '''
FROM python:3.12-slim

# Security hardening
RUN apt-get update && apt-get install -y --no-install-recommends \\
    && rm -rf /var/lib/apt/lists/* \\
    && useradd -r -s /bin/false sandbox

# Create sandbox directory
RUN mkdir -p /sandbox && chmod 755 /sandbox

# Copy executor script
COPY executor.py /sandbox/executor.py
RUN chmod +x /sandbox/executor.py

# Set up non-root user
USER nobody:nogroup

# Disable network and limit capabilities
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /sandbox
'''
        
        executor_script = '''#!/usr/bin/env python3
"""
Executor script for sandboxed code execution.
"""
import json
import sys
import traceback
from pathlib import Path

def main():
    if len(sys.argv) != 4:
        print("Usage: executor.py <code_file> <inputs_file> <output_file>", file=sys.stderr)
        sys.exit(1)
    
    code_file = Path(sys.argv[1])
    inputs_file = Path(sys.argv[2])
    output_file = Path(sys.argv[3])
    
    try:
        # Read code and inputs
        code = code_file.read_text()
        inputs = json.loads(inputs_file.read_text())
        
        # Prepare execution namespace
        namespace = {'__inputs__': inputs}
        
        # Capture stdout/stderr
        import io
        old_stdout = sys.stdout
        old_stderr = sys.stderr
        captured_stdout = io.StringIO()
        captured_stderr = io.StringIO()
        
        try:
            sys.stdout = captured_stdout
            sys.stderr = captured_stderr
            
            # Execute the code
            exec(code, namespace)
            
        finally:
            sys.stdout = old_stdout
            sys.stderr = old_stderr
        
        # Write output
        output_data = {
            'success': True,
            'stdout': captured_stdout.getvalue(),
            'stderr': captured_stderr.getvalue(),
            'namespace': {k: str(v) for k, v in namespace.items() if not k.startswith('__')}
        }
        
    except Exception as e:
        output_data = {
            'success': False,
            'stdout': '',
            'stderr': traceback.format_exc(),
            'error': str(e)
        }
    
    # Write output file
    try:
        output_file.write_text(json.dumps(output_data))
    except Exception:
        pass  # Fail silently if we can't write output

if __name__ == '__main__':
    main()
'''
        
        # Create temporary directory with Dockerfile and executor
        with tempfile.TemporaryDirectory() as build_dir:
            dockerfile_path = Path(build_dir) / "Dockerfile"
            executor_path = Path(build_dir) / "executor.py"
            
            dockerfile_path.write_text(dockerfile_content)
            executor_path.write_text(executor_script)
            
            # Build image
            try:
                await asyncio.get_event_loop().run_in_executor(
                    None,
                    lambda: self.client.images.build(
                        path=str(build_dir),
                        tag=self.SANDBOX_IMAGE,
                        rm=True,
                        quiet=False
                    )
                )
                self.logger.info(f"Successfully built sandbox image: {self.SANDBOX_IMAGE}")
            except Exception as e:
                raise SandboxError(f"Failed to build sandbox image: {e}")
    
    def cleanup(self) -> None:
        """Clean up any remaining containers."""
        for container_id in self.containers_to_cleanup[:]:
            try:
                container = self.client.containers.get(container_id)
                container.remove(force=True)
                self.containers_to_cleanup.remove(container_id)
            except Exception as e:
                self.logger.warning(f"Failed to clean up container {container_id}: {e}")


class ProcessSandbox(Sandbox):
    """Subprocess-based sandbox for lightweight execution (less secure)."""
    
    def __init__(self, resource_limits: Optional[ResourceLimits] = None):
        """
        Initialize process sandbox.
        
        Args:
            resource_limits: Resource constraints for execution
        """
        super().__init__(resource_limits)
        
    async def execute(self, code: str, inputs: Optional[Dict[str, Any]] = None) -> SandboxResult:
        """
        Execute code in a subprocess.
        
        This is less secure than Docker but useful for development/testing.
        
        Args:
            code: Python code to execute
            inputs: Optional input data for the code
            
        Returns:
            SandboxResult containing execution outcome
        """
        import subprocess
        import sys
        import os
        
        start_time = time.time()
        
        try:
            # Prepare code with inputs
            if inputs:
                full_code = f"__inputs__ = {json.dumps(inputs)}\n{code}"
            else:
                full_code = f"__inputs__ = {{}}\n{code}"
            
            # Execute in subprocess (simplified - no resource limits for cross-platform compatibility)
            process = await asyncio.create_subprocess_exec(
                sys.executable, '-c', full_code,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            
            try:
                stdout, stderr = await asyncio.wait_for(
                    process.communicate(),
                    timeout=self.resource_limits.timeout_seconds
                )
            except asyncio.TimeoutError:
                process.kill()
                await process.wait()
                execution_time = time.time() - start_time
                return SandboxResult(
                    success=False,
                    return_code=-1,
                    execution_time=execution_time,
                    error_message=f"Execution timed out after {self.resource_limits.timeout_seconds} seconds"
                )
            
            execution_time = time.time() - start_time
            
            return SandboxResult(
                success=(process.returncode == 0),
                stdout=stdout.decode('utf-8', errors='replace')[:self.resource_limits.max_output_size],
                stderr=stderr.decode('utf-8', errors='replace')[:self.resource_limits.max_output_size],
                return_code=process.returncode,
                execution_time=execution_time
            )
            
        except Exception as e:
            execution_time = time.time() - start_time
            return SandboxResult(
                success=False,
                execution_time=execution_time,
                error_message=f"Process execution failed: {str(e)}"
            )
    
    def _parse_memory_limit(self, memory_limit: str) -> int:
        """Parse memory limit string to bytes."""
        memory_limit = memory_limit.lower()
        multiplier = 1
        
        if memory_limit.endswith('k'):
            multiplier = 1024
            memory_limit = memory_limit[:-1]
        elif memory_limit.endswith('m'):
            multiplier = 1024 * 1024
            memory_limit = memory_limit[:-1]
        elif memory_limit.endswith('g'):
            multiplier = 1024 * 1024 * 1024
            memory_limit = memory_limit[:-1]
        
        try:
            return int(float(memory_limit) * multiplier)
        except ValueError:
            return 256 * 1024 * 1024  # Default 256MB
    
    def cleanup(self) -> None:
        """Process sandbox doesn't need cleanup."""
        pass


def create_sandbox(
    sandbox_type: str = "docker", 
    resource_limits: Optional[ResourceLimits] = None
) -> Sandbox:
    """
    Factory function to create a sandbox instance.
    
    Args:
        sandbox_type: Type of sandbox ("docker" or "process")
        resource_limits: Resource constraints for execution
        
    Returns:
        Sandbox instance
        
    Raises:
        SandboxError: If sandbox type is unsupported or requirements not met
    """
    if sandbox_type == "docker":
        return DockerSandbox(resource_limits)
    elif sandbox_type == "process":
        return ProcessSandbox(resource_limits)
    else:
        raise SandboxError(f"Unsupported sandbox type: {sandbox_type}")